# Generated by Django 3.0.3 on 2020-08-24 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expedition',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='name',
        ),
    ]
