# Generated by Django 3.0.3 on 2020-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedition', '0002_auto_20200824_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expedition',
            options={'verbose_name_plural': 'Expeditions'},
        ),
        migrations.AddField(
            model_name='expedition',
            name='goal',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expedition',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.CharField(default='no description', max_length=1000),
        ),
    ]
